### ISSUE TITLE
Not working on an french server (and probably on most non-english ones)

### ISSUE THREAD

**Issue by dvasseur** [StevenJDH/C2-Validator#1]
When running the tool on a french Qlik Sense server, I've got this error:
`Error: No certificate binding found on port 4242. Make sure you are running this on your Qlik Sense server.`

Looking at the source code, the command used to retrieve the certificate hash is:
`shell.Run("netsh http show sslcert ipport=0.0.0.0:4242 | findstr Hash"`
(getting certificate on port 4242 and looking for the line containing 'Hash')

The result of this command on my server is
`...`
 `**Hachage** du certificat             : xxxx...`
('Hachage' is the french word for 'Hash')

I don't have Visual Studio on this computer so I'm not able to check if that would solve the issue, but I'm pretty sure it would.

**Comment by StevenJDH** [comment]
Thank you for reporting the issue, this is an important issue that will be resolved shortly so that it works reliably for not English systems.

**Comment by StevenJDH** [comment]
Issue should now be fixed in the 1.0.1.20031 release.
