### ISSUE TITLE
Still not working for non-english systems

### ISSUE THREAD

**Issue by dvasseur** [StevenJDH/C2-Validator#2]
There is another issue for non-english systems here:
https://github.com/StevenJDH/C2-Validator/blob/5d53a52523c000d9a1ef7012b5d99bc33a7baed0/C2%20Validator/Program.cs#L44

On my French server, "FriendlyName" is translated to``Contraintes de base`` and thus, checks are failing.

The following code would fix the issue:
`` if (extension.Oid.Value != "2.5.29.19") continue; // "2.5.29.19" = "Basic Constraints"``

**Comment by StevenJDH** [comment]
Thank you again for reporting this and the suggested fix, this has been very helpful. I will investigate further and do additional tests here shortly.

**Comment by StevenJDH** [comment]
Issue should now be fixed in the 1.0.2.20032 release. I've tested it on two French servers, one with the certificate issue and one without the issue, and both tests produced the expected results.
