### ISSUE TITLE
Command to skip "press any key" or just return simple bolean value

### ISSUE THREAD

**Issue by GustavGager** [StevenJDH/C2-Validator#3]
I would like to run this program on a series of machines and take different actions depending on the outcome.
Is it possible to add a command line parameter to ignore the "press any key to continue"? Or even better, just let the program return 1 or 0 depending on if the certificate is valid or not?

**Comment by StevenJDH** [comment]
This is a great idea. I will implement this most likely in the next release, but there may be some delay as I am with other tasks at the moment. Thank you for suggesting this.

**Comment by GustavGager** [comment]
I understand. Would be great if it could be implemented 👍

**Comment by StevenJDH** [comment]
I've started work on the command line support. It will return 0 on pass and 1 on fail as well as higher values for error logging purposes. The only console output will be any errors encountered, but the logo, certificate information, status messages, and the pause for exit will be skipped. Does this sound like what you were looking for?

**Comment by StevenJDH** [comment]
As per my reply above, this feature is now available in the 1.1.0.20041 release. Please see the wiki article [Silent Mode](https://github.com/StevenJDH/C2-Validator/wiki/Silent-Mode) for more information on how this feature works.
